### ISSUE TITLE
Spotify module

### ISSUE THREAD

**Issue by stevetoro** [daveoy/react-capstone-jammming#1]
https://github.com/daveoy/react-capstone-jammming/blob/master/src/util/Spotify.js#L66-L87

The advantage of using `Promise`s over the callback pattern is that you can avoid these deeply nested blocks of code. When you call `fetch` inside of a `.then()`, you don't need to chain its `.then()` to the inner `fetch`, but rather to the outer `.then()`. This lets you write a simpler, more synchronous looking code and avoids the "callback hell".

For example, the above block of code could look like this:

```javascript
	savePlaylist: function(playlistName,trackURIs){
		// make sure we have access token set
		this.getAccessToken();
		// set up headers
		let headers = {
			Authorization: `Bearer ${accessToken}`
		}
		let userID;
		// do a get to access our userID
		fetch('https://api.spotify.com/v1/me',{headers:headers})
			.then(response => response.json())
			.then(jsonResponse => {
				userID = jsonResponse.id
				// let spotify know we're sending json
				headers['Content-Type'] = 'application/json';
				// set up the post data
				let postData = {
					name: playlistName,
				}
				// do the call
				return fetch('https://api.spotify.com/v1/users/' + userID + '/playlists', {
					headers: headers,
					method: 'POST',
					body: JSON.stringify(postData),
				})
			})
			.then(response => response.json())
			.then(jsonResponse => {
				let playlistID = jsonResponse.id;
				// get our postData ready to add the tracks
				let postData = {
					uris: trackURIs,
				}
				// do the call
				return fetch('https://api.spotify.com/v1/users/' + userID + '/playlists/' + playlistID + '/tracks', {
					headers: headers,
					method: 'POST',
					body: JSON.stringify(postData),
				})
			})
			.then(response => response.json())
			.then(jsonResponse => console.log(jsonResponse));
```

Notice that all of the chained `.then()`s are at the same level of indentation. They're not nested inside of each other even if one `.then()` calls another `fetch`. Just return the `fetch` and you can continue along the main chain, which reduces the complexity of the asynchronous call.

**Comment by daveoy** [comment]
yeah see i couldn't figure out a way to get variables outside of the callbacks set for use to simplify this... the scope changes were doing my head in so i figured i'd just rattle through it in one go. i like the idea of returning the fetch (promise), i'll try that out next time i have to chain some api calls together
