### ISSUE TITLE
Searching for tracks

### ISSUE THREAD

**Issue by stevetoro** [daveoy/react-capstone-jammming#2]
https://github.com/daveoy/react-capstone-jammming/blob/master/src/Components/App/App.js#L63-L72

Nice job remembering that the `Spotify.search()` method returns a `Promise` and properly chaining a `.then()` before setting your state 👍 

Consider renaming the `results` variable as `searchResults` so that you can benefit from using ES6's property/value shorthand syntax here:

```javascript
this.setState({ searchResults });
```

You can use this whenever you need an object whose key is the same as its value (i.e. `{ searchResults: searchResults }` ) and you might find it makes your code more terse.

**Comment by daveoy** [comment]
ooo that's a great tip, thanks for that
