### ISSUE TITLE
Saving playlists to user account

### ISSUE THREAD

**Issue by stevetoro** [daveoy/react-capstone-jammming#5]
https://github.com/daveoy/react-capstone-jammming/blob/master/src/Components/App/App.js#L52-L62

Don't forget that `Spotify.savePlaylist` returns a `Promise`, so ideally you should use `.then` to reset the `Playlist`'s state _after_ the request is resolved. 

Reconsider clearing the `searchResults` state. It's possible that someone might want to use the current search results in a new playlist.

Consider using a combination of `.map`, ES6's arrow function, and implicit return to get all the track IDs in one single, neat line of code.

For example:

```javascript
let trackURIs = this.state.playlistTracks.map(track => track.uri);
```

**Comment by daveoy** [comment]
right, in the case something goes wrong with saving the playlist, we want to make sure we don't clear it.... good point.
