### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by stevetoro** [daveoy/react-capstone-jammming#7]
Satisfactory

Heads up: Your application is not deployed to your redirectUrl (`http://dy.surge.sh`). So when someone tries to run your project locally, they are redirected to a broken page. I have my own Spotify developer credentials, so I just replaced them and redirected to my localhost, but you can't reasonably expect another programmer or potential employer to go through this trouble. Make sure the code you're pushing to Github is ready to use!

Besides that initial setup, it's fairly easy to get started searching for songs, adding them to playlists and finally adding those playlists to an actual Spotify account. Good job!

**Comment by daveoy** [comment]
yeah... i couldn't seem to get that surge thing to work... thanks for working around that one for me
